version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: inputs_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=input-metadata
    ports:
      - "5431:5432"
  inputs:
    container_name: inputs_container
    image: petreskiv/code:1.0-SNAPSHOT-5.1
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/input-metadata
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    ports:
      - "8081:8081"
    depends_on:
      - postgres