version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=input-metadata
    ports:
      - "5431:5432"
  inputs:
    image: petreskiv/code:1.0-SNAPSHOT-3.1
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5431/input-metadata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dbuser
    ports:
      - "8081:8081"
    depends_on:
      - postgres