apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-inputs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-inputs
  template:
    metadata:
      labels:
        app: code-inputs
    spec:
      containers:
        - image: petreskiv/code:1.0-SNAPSHOT-11.1
          name: code-inputs
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: code
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://34.67.168.202:8080
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://10.64.240.3:5432/code-inputs
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: laptop
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
---

apiVersion: v1
kind: Service
metadata:
  name: code-inputs
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: code-inputs
