kumuluzee:
  name: code-inputs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/InputMetadataPS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
